server:
  port: 7072
  servlet:
    contextPath: /deliver

application:
  name: deliver-service

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/delivery_deliver?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:3141593}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      use_sql_comments: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    topic:
      name: deliveryTopic
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:9092
      properties:
        retry.backoff.ms: 1000
security:
  token:
    expire-length: 3600000

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  server:
    port: 7172