server:
  port: 7073
  servlet:
    contextPath: /notification

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: summodern
    password: k10091984
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  kafka:
    topic:
      name: deliveryTopic
    producer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:9092
      properties:
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:localhost}:9092
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
      group-id: notification-group-id

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  server:
    port: 7173