version: '3.7'

services:

  db:
    image: mariadb
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DELIVERY_DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  gateway:
    build: ./gateway
    networks:
      - backend
    ports:
      - 7007:7007

  user-service:
    build: ./user-service
    depends_on:
      - gateway
      - db
    networks:
      - backend
    ports:
      - 7071:7071

  deliver-service:
    build: ./deliver-service
    depends_on:
      - gateway
      - db
    networks:
      - backend
    ports:
      - 7072:7072

  notification-service:
    build: ./notification-service
    depends_on:
      - gateway
      - db
    networks:
      - backend
    ports:
      - 7073:7073

volumes:
  db-data:

networks:
  backend:
  back:
    driver: bridge