version: '3.7'

services:

  db:
    image: mariadb
    container_name: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${DELIVERY_DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  gateway:
    build: ./gateway-service
    networks:
      - backend
    ports:
      - 8180:8180

  user-service:
    build: ./user-service
    depends_on:
      - gateway
      - db
    networks:
      - backend
    ports:
      - 8181:8181

  deliver-service:
    build: ./deliver-service
    depends_on:
      - gateway
      - db
    networks:
      - backend
    ports:
      - 8182:8182


volumes:
  db-data:

networks:
  backend:
  back:
    driver: bridge