server:
  port: 7007

spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: userModule
          uri: http://localhost:7071/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/user/**
        - id: deliverModule
          uri: http://localhost:7072/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/deliver/**
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  server:
    port: 7107