apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-gatewy-k8s
spec:
  selector:
    matchLabels:
      app: delivery-gatewy-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: delivery-gatewy-k8s
    spec:
      containers:
        - name: delivery-gatewy-k8s
          image: delivery_gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deliver-k8s
spec:
  selector:
    matchLabels:
      app: delivery-deliver-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: delivery-deliver-k8s
    spec:
      containers:
        - name: delivery-deliver-k8s
          image: delivery_deliver-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7071
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-user-k8s
spec:
  selector:
    matchLabels:
      app: delivery-user-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: delivery-user-k8s
    spec:
      containers:
        - name: delivery-deliver-k8s
          image: delivery_user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7072
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-notification-k8s
spec:
  selector:
    matchLabels:
      app: delivery-notification-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: delivery-notification-k8s
    spec:
      containers:
        - name: delivery-notification-k8s
          image: delivery_notification-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7073