server:
  port: 7071
  servlet:
    contextPath: /user

application:
  name: user-service

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/delivery_security?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:3141593}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
security:
  token:
    expire-length: 3600000
