server:
  port: 8182
  servlet:
    contextPath: /deliver

application:
  name: delivery_deliver

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/delivery_deliver?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 3141593
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Baku
app:
  jwtExpirationInMs: 720000